### ISSUE TITLE
Failed to load file (stonequarry.json) (1.18.2-rc4)

### ISSUE THREAD

**Issue by ArchieBeepBoop** [DArkHekRoMaNT/StoneQuarry#15]
### Mod Version

3.0.0

### Game Version

1.18.2-rc4

### OS

Windows

### Play mode

Multiplayer

### Problem

In a windows hosted dedicated server, it seems that one of Stone Quarry's json files will fail to load due to a failed conversion from an integer to an object.

Logs attached.

### Logs

```bash
10.5.2023 14:25:12 [Error] [commonlib] Failed loading file (stonequarry.json), error Newtonsoft.Json.JsonSerializationException: Error converting value 512 to type 'CommonLib.Config.ConfigUtil+JsonConfigValue`1[System.Object]'. Path 'RubbleStorageMaxSize', line 33, position 29. ---> System.ArgumentException: Could not cast or convert from System.Int64 to CommonLib.Config.ConfigUtil+JsonConfigValue`1[System.Object].
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Vintagestory.Common.APIBase.LoadModConfig[T](String filename) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\APIBase.cs:line 110
   at CommonLib.Utils.ModDataUtil.LoadOrCreateConfig[T](ICoreAPI api, String file, ILogger logger, T defaultConfig) in CommonLib/Utils/ModDataUtil.cs:line 16. Will initialize new one
```

### Mods

```bash
CommonLib
StoneQuarry
QPTech
```

**Comment by DArkHekRoMaNT** [comment]
Try deleting this config file (stonequarry.json from VintagestoryData/ModConfig). It may be corrupt/outdated

**Comment by ArchieBeepBoop** [comment]
You're absolutely correct, it was corrupted it seems.
